# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D2yPGwg2vMWGHo3D_MT8Dc7a1vh16UsU
"""



import pandas as pd
data = pd.Series([1, 2, 3, 4], index=['a', 'b', 'a', 'c'])
print(data)
print(data['a'])

dict_data = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
limited_keys = ['a', 'c', 'e']

limited_series = pd.Series(dict_data, index=limited_keys)
print(limited_series)

squares_series = pd.Series([i**2 for i in range(1, 21)])
print(squares_series)
filltered_series = squares_series[squares_series.index % 3 != 0]
print(filtered_series)

students_df = pd.read_csv("students.csv")
print(students_df.head(3))
print(students_df.tall(2))
students_df.info()

or (int i=1; i<11; i++) {
                        for (int j=1; j<11; j++) {
                                x=i*2+(int)(Random.value);
                                y=j*2+(int)(Random.value);